name: Publish Code Coverage Reports to GitHub Pages

on:
  workflow_call:
    inputs:
      HTML_ARTIFACT_ID:
        type: string
        required: true
      JSON_ARTIFACT_ID:
        type: string
        required: true
      BRANCH_NAME:
        type: string
        required: true
      RUN_ID:
        type: string
        required: true

jobs:
  push-to-pages:
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download JSON Report
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.JSON_ARTIFACT_ID }}
          path: _data/coverage/
      - name: Download HTML Report
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.HTML_ARTIFACT_ID }}
          path: coverage/
      - name: Push to GitHub Pages Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update code coverage report for main"
          git pull origin gh-pages --rebase -s recursive -X ours
          git push
          echo "Report URL: https://enterprise-cmcs.github.io/macpro-mako/coverage/" >> "$GITHUB_STEP_SUMMARY"
